# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails', '~> 5.2.0'

gem 'bootsnap', require: false

gem 'jbuilder', '~> 2.5'
gem 'mysql2', '>= 0.3.18', '< 0.6.0'
gem 'puma', '~> 3.7'
gem 'rails-i18n'
gem 'sass-rails', '~> 5.0'
gem 'tzinfo-data'
gem 'uglifier', '>= 1.3.0'

gem 'canonical-rails'
gem 'locale_kit'
gem 'meta-tags'
gem 'slim-rails'
gem 'stripe'
gem 'dotenv-rails', require: 'dotenv/rails-now'

# For deployment
gem 'aws-sdk-core', '~> 3.0'
gem 'aws-sdk-s3'
gem 'aws-sdk-codedeploy'

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  gem 'factory_bot_rails'
  gem 'rspec-rails'

  # pry
  gem 'pry-rails'
  gem 'pry-byebug'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'

  gem 'rubocop', require: false
  gem 'spring-commands-rspec', require: false
end

group :test do
  gem 'capybara'
  gem 'database_rewinder'
  gem 'ffaker'
  gem 'rails-controller-testing'
  gem 'selenium-webdriver'
  gem 'simplecov', require: false
  gem 'stripe-ruby-mock', require: 'stripe_mock'
  # test 用の便利メソッドたちを利用する
  gem 'shoulda-matchers', require: false
  gem 'rspec_junit_formatter'
end
